### ISSUE TITLE
Error when using /money (same with /pay)

### ISSUE THREAD

**Issue by Eufranio** [notabadminer/UniversalCoinsVaultPlugin#3]
```
ios4SP issued server command: /money
[00:27:18 ERROR]: Comando money falhou:                                                   java.lang.NoClassDefFoundError: universalcoins/util/UniversalAccounts
        at universalcoinseconomy.UCEconomy.hasAccount(UCEconomy.java:231) ~[UniversalCoins.jar:?]
        at universalcoinseconomy.UCEconomy.hasAccount(UCEconomy.java:226) ~[UniversalCoins.jar:?]
        at com.earth2me.essentials.register.payment.methods.VaultEco.hasAccount(VaultEco.java:82) ~[Essentials.jar:?]
        at com.earth2me.essentials.User._getMoney(User.java:422) ~[Essentials.jar:?]              at com.earth2me.essentials.User.getMoney(User.java:398) ~[Essentials.jar:?]
        at com.earth2me.essentials.commands.Commandbalance.run(Commandbalance.java:41) ~[Essentials.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:149) ~[Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:505) [Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:380) [Essentials.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.57]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.57]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by spannerman79** [comment]
What was your solution seeing as you closed your issue?

**Comment by Eufranio** [comment]
I was using an newer version of UniversalCoins [(here)](https://github.com/GameModsBR/UniversalCoinsServer), it has a lot of bug and error fixes. So, a dev made a custom-made mod for me and my server: [(here)](https://github.com/MagiTechServer/UniversalCoinsGameModsBridge)

**Comment by spannerman79** [comment]
Thanks.  That way if anyone else has the same issue or is using google to search for the same problem they can have a quicker answer :smile:
